version: '3'

services:
  key-regis:
    image: satangtech/key-regis:0.0.1
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./.env:/app/.env
      - ./privkey.ts:/app/privkey.ts
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - ./.mongo:/data/db
