version: '3'

services:

  key-regis:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mongo
      - firovm

  mongo:
    image: mongo:5

  firovm:
    image: satangtech/firovm-poa:2b225f0791ebb560d299780364965254cace247f
    tty: true
    stdin_open: true
    volumes:
      - ./.firovm:/firovm
    ports:
      - 1234:1234
      - 11000:11000

  it-test:
    build: .
    stdin_open: true
    tty: true
    command: npm run test:integration
